-- Create table for storing selected QA team members
CREATE TABLE IF NOT EXISTS public.qa_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    hubstaff_name TEXT NOT NULL,
    hubstaff_user_id BIGINT,
    department TEXT DEFAULT 'QA',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.qa_members ENABLE ROW LEVEL SECURITY;

-- Allow everything for anon (dev simplified)
CREATE POLICY "Enable all access for all users" ON public.qa_members
    FOR ALL USING (true) WITH CHECK (true);
