-- Create global_pcs table for storing global Project Coordinator names
CREATE TABLE IF NOT EXISTS public.global_pcs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for security
ALTER TABLE public.global_pcs ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all authenticated users to view PCs
CREATE POLICY "All users can view PCs" ON public.global_pcs
    FOR SELECT
    USING (auth.role() = 'authenticated');

-- Create policy to allow only super admins to insert PCs
CREATE POLICY "Super admins can insert PCs" ON public.global_pcs
    FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.user_profiles 
            WHERE id = auth.uid() AND role = 'super_admin'
        )
    );

-- Create policy to allow only super admins to delete PCs
CREATE POLICY "Super admins can delete PCs" ON public.global_pcs
    FOR DELETE
    USING (
        EXISTS (
            SELECT 1 FROM public.user_profiles 
            WHERE id = auth.uid() AND role = 'super_admin'
        )
    );

-- Create index on name for faster queries
CREATE INDEX IF NOT EXISTS idx_global_pcs_name ON public.global_pcs(name);

-- Insert some default PCs (optional)
-- Uncomment and modify as needed:
-- INSERT INTO public.global_pcs (name) 
-- VALUES ('John Doe'), ('Jane Smith')
-- ON CONFLICT (name) DO NOTHING;
