-- Create team_subphases table for storing team-specific sub-phases
CREATE TABLE IF NOT EXISTS public.team_subphases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id UUID NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Add foreign key constraint to teams table
    CONSTRAINT fk_team FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE,
    
    -- Ensure unique sub-phase names per team
    CONSTRAINT unique_subphase_per_team UNIQUE (team_id, name)
);

-- Enable RLS for multi-tenancy support
ALTER TABLE public.team_subphases ENABLE ROW LEVEL SECURITY;

-- Create policy to allow users to view sub-phases for their team
CREATE POLICY "Users can view their team's sub-phases" ON public.team_subphases
    FOR SELECT
    USING (
        team_id IN (
            SELECT team_id FROM public.user_profiles 
            WHERE id = auth.uid()
        )
    );

-- Create policy to allow team admins to insert sub-phases
CREATE POLICY "Team admins can insert sub-phases" ON public.team_subphases
    FOR INSERT
    WITH CHECK (
        team_id IN (
            SELECT team_id FROM public.user_profiles 
            WHERE id = auth.uid() AND (role = 'admin' OR role = 'super_admin')
        )
    );

-- Create policy to allow team admins to delete sub-phases
CREATE POLICY "Team admins can delete sub-phases" ON public.team_subphases
    FOR DELETE
    USING (
        team_id IN (
            SELECT team_id FROM public.user_profiles 
            WHERE id = auth.uid() AND (role = 'admin' OR role = 'super_admin')
        )
    );

-- Create index on team_id for faster queries
CREATE INDEX IF NOT EXISTS idx_team_subphases_team_id ON public.team_subphases(team_id);

-- Insert some default sub-phases for existing teams (optional)
-- Uncomment and modify as needed:
-- INSERT INTO public.team_subphases (team_id, name) 
-- SELECT id, 'Smoke Test' FROM public.teams WHERE NOT EXISTS (
--     SELECT 1 FROM public.team_subphases WHERE team_id = teams.id AND name = 'Smoke Test'
-- );
