-- Create team_members table
CREATE TABLE IF NOT EXISTS team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(team_id, name)
);

-- RLS Policies
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;

-- Allow users to view members of their own team
CREATE POLICY "Users can view their own team members" 
ON team_members FOR SELECT 
USING (
    team_id IN (
        SELECT team_id FROM user_profiles WHERE id = auth.uid()
    )
);

-- Allow users to insert members into their own team
CREATE POLICY "Users can insert members into their own team" 
ON team_members FOR INSERT 
WITH CHECK (
    team_id IN (
        SELECT team_id FROM user_profiles WHERE id = auth.uid()
    )
);

-- Allow users to delete members from their own team
CREATE POLICY "Users can delete members from their own team" 
ON team_members FOR DELETE 
USING (
    team_id IN (
        SELECT team_id FROM user_profiles WHERE id = auth.uid()
    )
);
