-- ==========================================
-- QATrack Project - Full Database Schema
-- ==========================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLES

-- Teams
CREATE TABLE IF NOT EXISTS public.teams (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- User Profiles (extends Supabase Auth)
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id),
    email TEXT,
    full_name TEXT,
    role TEXT CHECK (role IN ('super_admin', 'team_admin', 'member', 'admin')),
    team_id UUID REFERENCES teams(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Projects (Base Table)
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    hubstaff_id BIGINT,
    team_id UUID REFERENCES teams(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT projects_hubstaff_team_unique UNIQUE (hubstaff_id, team_id)
);

-- Tasks
CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name TEXT NOT NULL,
    project_type TEXT,
    sub_phase TEXT,
    priority TEXT,
    pc TEXT,
    assigned_to TEXT,
    assigned_to2 TEXT,
    additional_assignees TEXT[],
    status TEXT DEFAULT 'In Progress',
    start_date DATE,
    end_date DATE,
    actual_completion_date DATE,
    include_saturday BOOLEAN DEFAULT false,
    include_sunday BOOLEAN DEFAULT false,
    actual_start_date DATE,
    actual_end_date DATE,
    start_time TEXT DEFAULT '09:30',
    end_time TEXT DEFAULT '18:30',
    completed_at TIMESTAMP WITH TIME ZONE,
    comments TEXT,
    current_updates TEXT,
    bug_count INTEGER DEFAULT 0,
    html_bugs INTEGER DEFAULT 0,
    functional_bugs INTEGER DEFAULT 0,
    deviation_reason TEXT,
    sprint TEXT,
    sprint_link TEXT,
    days_allotted NUMERIC(10, 2) DEFAULT 0,
    time_taken TEXT DEFAULT '00:00:00',
    days_taken NUMERIC(10, 2) DEFAULT 0,
    deviation NUMERIC(10, 2) DEFAULT 0,
    activity_percentage NUMERIC(5, 2) DEFAULT 0,
    team_id UUID REFERENCES teams(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Team Members
CREATE TABLE IF NOT EXISTS public.team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(team_id, name)
);

-- Leaves
CREATE TABLE IF NOT EXISTS public.leaves (
    id BIGSERIAL PRIMARY KEY,
    team_member_id TEXT NOT NULL, -- Hubstaff user ID
    team_member_name TEXT NOT NULL,
    leave_date DATE NOT NULL,
    leave_type TEXT NOT NULL CHECK (leave_type IN (
        'Full Day Casual Leave', 
        'Full Day Sick Leave', 
        'Unplanned Leave', 
        'Half Day Morning Session Casual Leave', 
        'Half Day Morning Session Sick Leave', 
        'Half Day Afternoon Session Casual Leave', 
        'Half Day Afternoon Session Sick Leave'
    )),
    reason TEXT,
    team_id UUID REFERENCES teams(id),
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Project Overview
CREATE TABLE IF NOT EXISTS public.project_overview (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_name TEXT NOT NULL,
    team_id UUID REFERENCES teams(id) ON DELETE CASCADE,
    location TEXT CHECK (location IN ('Dubai', 'Cochin')),
    pc TEXT,
    allotted_time_days NUMERIC(10, 2),
    tl_confirmed_effort_days NUMERIC(10, 2),
    blockers TEXT,
    expected_effort_days NUMERIC(10, 2),
    hubstaff_budget TEXT,
    committed_days NUMERIC(10, 2),
    fixing_text TEXT,
    live_text TEXT,
    budget_text TEXT,
    started_date DATE,
    project_type TEXT,
    category TEXT,
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(project_name, team_id)
);

-- Global PCs
CREATE TABLE IF NOT EXISTS public.global_pcs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Team Sub-phases
CREATE TABLE IF NOT EXISTS public.team_subphases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (team_id, name)
);

-- Hubstaff Tokens
CREATE TABLE IF NOT EXISTS public.hubstaff_tokens (
    id INT PRIMARY KEY DEFAULT 1,
    access_token TEXT NOT NULL,
    refresh_token TEXT NOT NULL,
    expires_at BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT single_row CHECK (id = 1)
);

-- QA Members
CREATE TABLE IF NOT EXISTS public.qa_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    hubstaff_name TEXT NOT NULL,
    hubstaff_user_id BIGINT,
    department TEXT DEFAULT 'QA',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. VIEWS

-- Project Statistics View
CREATE OR REPLACE VIEW public.project_task_stats AS
SELECT
    project_name,
    ARRAY_AGG(DISTINCT assignee) FILTER (WHERE assignee IS NOT NULL AND assignee != '') AS resources,
    COALESCE(SUM(activity_percentage), 0) AS total_activity_percentage,
    COALESCE(
        SUM(
            EXTRACT(EPOCH FROM 
                CASE 
                    WHEN time_taken IS NULL OR time_taken = '' THEN '00:00:00'::interval 
                    ELSE time_taken::interval 
                END
            )
        ) / 3600.0 / 8.0, 
        0
    ) AS total_time_taken_days,
    COALESCE(SUM(days_allotted), 0) AS total_allotted_days,
    COUNT(*) AS task_count
FROM (
    SELECT id, project_name, assigned_to AS assignee, activity_percentage, time_taken, days_allotted FROM public.tasks
    UNION ALL
    SELECT id, project_name, assigned_to2 AS assignee, activity_percentage, time_taken, days_allotted FROM public.tasks
    UNION ALL
    SELECT t.id, t.project_name, unnested_assignee AS assignee, t.activity_percentage, t.time_taken, t.days_allotted
    FROM public.tasks t, UNNEST(t.additional_assignees) AS unnested_assignee
) AS all_assignees
GROUP BY project_name;

-- Project Overview with Stats View
CREATE OR REPLACE VIEW public.project_overview_with_stats AS
SELECT 
    po.*,
    (SELECT COUNT(*) FROM public.tasks WHERE project_name = po.project_name AND team_id = po.team_id) as task_count,
    (SELECT STRING_AGG(DISTINCT assignee, ', ') 
     FROM (
         SELECT assigned_to as assignee FROM public.tasks WHERE project_name = po.project_name AND team_id = po.team_id AND assigned_to IS NOT NULL
         UNION
         SELECT assigned_to2 as assignee FROM public.tasks WHERE project_name = po.project_name AND team_id = po.team_id AND assigned_to2 IS NOT NULL
     ) assignees
    ) as resources
FROM public.project_overview po;

-- 4. FUNCTIONS & TRIGGERS

-- Updated At Trigger Function
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply Updated At Trigger to Leaves
CREATE TRIGGER trigger_update_leaves_updated_at
    BEFORE UPDATE ON public.leaves
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- Apply Updated At Trigger to Project Overview
CREATE TRIGGER trigger_update_project_overview_updated_at
    BEFORE UPDATE ON public.project_overview
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- 5. ROW LEVEL SECURITY (RLS) MODELS

-- Enable RLS on all tables
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaves ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_overview ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.global_pcs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_subphases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hubstaff_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qa_members ENABLE ROW LEVEL SECURITY;

-- TEAMS Policies
CREATE POLICY "Users can view their own team" ON public.teams
    FOR SELECT USING (id IN (SELECT team_id FROM public.user_profiles WHERE id = auth.uid()));

-- USER_PROFILES Policies
CREATE POLICY "Users can view their own profile" ON public.user_profiles
    FOR SELECT USING (id = auth.uid());

-- PROJECTS Policies
CREATE POLICY "Users can view own team projects" ON public.projects
    FOR SELECT USING (team_id IN (SELECT team_id FROM public.user_profiles WHERE id = auth.uid()));
CREATE POLICY "Users can modify own team projects" ON public.projects
    FOR ALL USING (team_id IN (SELECT team_id FROM public.user_profiles WHERE id = auth.uid()));

-- TASKS Policies
CREATE POLICY "Users can view own team tasks" ON public.tasks
    FOR SELECT USING (team_id IN (SELECT team_id FROM public.user_profiles WHERE id = auth.uid()));
CREATE POLICY "Users can modify own team tasks" ON public.tasks
    FOR ALL USING (team_id IN (SELECT team_id FROM public.user_profiles WHERE id = auth.uid()));

-- TEAM_MEMBERS Policies
CREATE POLICY "Users can view own team members" ON public.team_members
    FOR SELECT USING (team_id IN (SELECT team_id FROM public.user_profiles WHERE id = auth.uid()));
CREATE POLICY "Users can modify own team members" ON public.team_members
    FOR ALL USING (team_id IN (SELECT team_id FROM public.user_profiles WHERE id = auth.uid()));

-- LEAVES Policies
CREATE POLICY "Allow authenticated users to read leaves" ON public.leaves
    FOR SELECT USING (true);
CREATE POLICY "Allow authenticated users to insert leaves" ON public.leaves
    FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow users to modify own leaves" ON public.leaves
    FOR ALL USING (created_by = auth.uid());

-- PROJECT_OVERVIEW Policies
CREATE POLICY "Users can view their team's project overview" ON public.project_overview
    FOR SELECT USING (team_id IN (SELECT team_id FROM public.user_profiles WHERE id = auth.uid()));
CREATE POLICY "Users can modify their team's project overview" ON public.project_overview
    FOR ALL USING (team_id IN (SELECT team_id FROM public.user_profiles WHERE id = auth.uid()));

-- GLOBAL_PCS Policies
CREATE POLICY "All users can view PCs" ON public.global_pcs
    FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Super admins can modify PCs" ON public.global_pcs
    FOR ALL USING (EXISTS (SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role = 'super_admin'));

-- TEAM_SUBPHASES Policies
CREATE POLICY "Users can view their team's sub-phases" ON public.team_subphases
    FOR SELECT USING (team_id IN (SELECT team_id FROM public.user_profiles WHERE id = auth.uid()));
CREATE POLICY "Team admins can modify sub-phases" ON public.team_subphases
    FOR ALL USING (team_id IN (SELECT team_id FROM public.user_profiles WHERE id = auth.uid() AND (role = 'admin' OR role = 'super_admin')));

-- HUBSTAFF_TOKENS Policies
CREATE POLICY "Enable all access for all users" ON public.hubstaff_tokens
    FOR ALL USING (true) WITH CHECK (true);

-- QA_MEMBERS Policies
CREATE POLICY "Allow read access to authenticated users" ON public.qa_members
    FOR SELECT USING (auth.role() = 'authenticated');

-- 6. GRANTS
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
